package com.EmosewaPixel.expertmodecore.items;

import com.EmosewaPixel.expertmodecore.ExpertModeCore;
import com.EmosewaPixel.expertmodecore.items.tools.*;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;

public class ItemRegistry {
    public static Item BRICK_MOLD;
    public static Item BRONZE_DUST;
    public static Item BRONZE_INGOT;
    public static Item BRONZE_NUGGET;
    public static Item BRONZE_AXE;
    public static Item BRONZE_HAMMER;
    public static Item BRONZE_HOE;
    public static Item BRONZE_PICK;
    public static Item BRONZE_SAW;
    public static Item BRONZE_SHOVEl;
    public static Item BRONZE_SWORD;
    public static Item COPPER_DUST;
    public static Item COPPER_INGOT;
    public static Item COPPER_NUGGET;
    public static Item CRUSHED_MAGMA_BLOCK;
    public static Item ELECTRUM_DUST;
    public static Item ELECTRUM_INGOT;
    public static Item ELECTRUM_NUGGET;
    public static Item ELECTRUM_AXE;
    public static Item ELECTRUM_HAMMER;
    public static Item ELECTRUM_HOE;
    public static Item ELECTRUM_PICK;
    public static Item ELECTRUM_SAW;
    public static Item ELECTRUM_SHOVEl;
    public static Item ELECTRUM_SWORD;
    public static Item GOLD_DUST;
    public static Item IRON_DUST;
    public static Item FLINT_AXE;
    public static Item FLINT_HAMMER;
    public static Item FLINT_HOE;
    public static Item FLINT_PICK;
    public static Item FLINT_SAW;
    public static Item FLINT_SHOVEl;
    public static Item FLINT_SWORD;
    public static Item NETHERRACK_DUST;
    public static Item SILVER_DUST;
    public static Item SILVER_INGOT;
    public static Item SILVER_NUGGET;
    public static Item STEEl_DUST;
    public static Item STEEL_INGOT;
    public static Item STEEL_NUGGET;
    public static Item STEEL_AXE;
    public static Item STEEL_HAMMER;
    public static Item STEEL_HOE;
    public static Item STEEL_PICK;
    public static Item STEEL_SAW;
    public static Item STEEL_SHOVEl;
    public static Item STEEL_SWORD;
    public static Item TIN_DUST;
    public static Item TIN_INGOT;
    public static Item TIN_NUGGET;
    public static Item UNFIRED_BRICK;

    public static void registry(RegistryEvent.Register<Item> e) {
        BRICK_MOLD = register(new SelfContainerItem("brick_mold"), e);
        BRONZE_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("bronze_dust"), e);
        BRONZE_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("bronze_ingot"), e);
        BRONZE_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("bronze_nugget"), e);
        BRONZE_AXE = register(new ModAxe(ExpertTiers.BRONZE, 7, -3.2F), e);
        BRONZE_HAMMER = register(new ModHammer(ExpertTiers.BRONZE, 7, -3.2F), e);
        BRONZE_HOE = register(new ModHoe(ExpertTiers.BRONZE, -2.0F), e);
        BRONZE_PICK = register(new ModPick(ExpertTiers.BRONZE, 1, -2.8F), e);
        BRONZE_SAW = register(new ModSaw(ExpertTiers.BRONZE, 3F, -3.2F), e);
        BRONZE_SHOVEl = register(new ModShovel(ExpertTiers.BRONZE, 3, -3.2F), e);
        BRONZE_SWORD = register(new ModSword(ExpertTiers.BRONZE, 3, -2.4F), e);
        COPPER_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("copper_dust"), e);
        COPPER_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("copper_ingot"), e);
        COPPER_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("copper_nugget"), e);
        CRUSHED_MAGMA_BLOCK = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("crushed_magma_cream"), e);
        ELECTRUM_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("electrum_dust"), e);
        ELECTRUM_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("electrum_ingot"), e);
        ELECTRUM_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("electrum_nugget"), e);
        ELECTRUM_AXE = register(new ModAxe(ExpertTiers.ELECTRUM, 6, -3.0F), e);
        ELECTRUM_HAMMER = register(new ModHammer(ExpertTiers.ELECTRUM, 6, -3.0F), e);
        ELECTRUM_HOE = register(new ModHoe(ExpertTiers.ELECTRUM, -3.0F), e);
        ELECTRUM_PICK = register(new ModPick(ExpertTiers.ELECTRUM, 1, -2.8F), e);
        ELECTRUM_SAW = register(new ModSaw(ExpertTiers.ELECTRUM, 3, -3.0F), e);
        ELECTRUM_SHOVEl = register(new ModShovel(ExpertTiers.ELECTRUM, 1.5F, -3.0F), e);
        ELECTRUM_SWORD = register(new ModSword(ExpertTiers.ELECTRUM, 3, -2.4F), e);
        FLINT_AXE = register(new ModAxe(ExpertTiers.FLINT, 6, -3.2F), e);
        FLINT_HAMMER = register(new ModHammer(ExpertTiers.FLINT, 6, -3.2F), e);
        FLINT_HOE = register(new ModHoe(ExpertTiers.FLINT, -3.0F), e);
        FLINT_PICK = register(new ModPick(ExpertTiers.FLINT, 1, -2.8F), e);
        FLINT_SAW = register(new ModSaw(ExpertTiers.FLINT, 3, -3.2F), e);
        FLINT_SHOVEl = register(new ModShovel(ExpertTiers.FLINT, 1.5F, -3.2F), e);
        FLINT_SWORD = register(new ModSword(ExpertTiers.FLINT, 3, -2.4F), e);
        GOLD_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("gold_dust"), e);
        IRON_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("iron_dust"), e);
        NETHERRACK_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("netherrack_dust"), e);
        SILVER_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("silver_dust"), e);
        SILVER_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("silver_ingot"), e);
        SILVER_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("silver_nugget"), e);
        STEEl_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("steel_dust"), e);
        STEEL_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("steel_ingot"), e);
        STEEL_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("steel_nugget"), e);
        STEEL_AXE = register(new ModAxe(ExpertTiers.STEEl, 6, -3.1F), e);
        STEEL_HAMMER = register(new ModHammer(ExpertTiers.STEEl, 6, -3.1F), e);
        STEEL_HOE = register(new ModHoe(ExpertTiers.STEEl, -1.0F), e);
        STEEL_PICK = register(new ModPick(ExpertTiers.STEEl, 1, -2.8F), e);
        STEEL_SAW = register(new ModSaw(ExpertTiers.STEEl, 3, -3.1F), e);
        STEEL_SHOVEl = register(new ModShovel(ExpertTiers.STEEl, 1.5F, -3.0F), e);
        STEEL_SWORD = register(new ModSword(ExpertTiers.STEEl, 3, -2.4F), e);
        TIN_DUST = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("tin_dust"), e);
        TIN_INGOT = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("tin_ingot"), e);
        TIN_NUGGET = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("tin_nugget"), e);
        UNFIRED_BRICK = register(new Item(new Item.Properties().group(ExpertModeCore.main)).setRegistryName("unfired_brick"), e);
    }

    private static Item register(Item item, RegistryEvent.Register<Item> e) {
        e.getRegistry().register(item);
        return item;
    }
}
